trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Your-Service-Connection-Name'
  appName: 'ecom-webapp-16btcs'
  resourceGroup: 'ecom-rg'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build App'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(System.DefaultWorkingDirectory)'
    displayName: 'Deploy to Azure'
